# bumpver.toml in project root

[bumpver]
current_version = "2022.9.24.0"
version_pattern = "YYYY.MM.DD.INC0[-TAG]"
commit_message = "bump: {new_version}"
commit = true
tag = false
push = false

[bumpver.file_patterns]
"package.json" = [
    '"version": "{version}"',
]
"bumpver.toml" = [
    'current_version = "{version}"',
]